// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { AboutSlint } from "std-widgets.slint";
import { Page } from "../widgets/page.slint";

export component AlbumPage inherits Page {
    // Title
    title: @tr("相册");
    description: @tr("Are you curious now? Check out the docs and getting starteds from the Github repository and the website https://slint.dev and try it yourself.");
    
    // layout
    // Content
    Text {
        text: @tr("WIP");
        font-size: 32px;
    }

    // Spacer
    Rectangle {}
}
