// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Switch, GridBox, ListView, ScrollView, HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

export component Page inherits VerticalBox {
    // properties
    preferred-width: 700px;

    // variables
    in property <string> title: "title";
    in property <string> description: "description";
    
    // layout
    VerticalLayout {
        HorizontalBox {
            Text {
                font-size: 20px;
                text <=> root.title;
            }
    
            // Spacer
            Rectangle { }

            Switch {
                horizontal-stretch: 0;
                text: @tr("Dark Mode");
                checked: Palette.color-scheme == ColorScheme.dark;
                toggled => {
                    Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
                    debug("color-scheme changed:", Palette.color-scheme);
                }
            }
        }

        @children
    }
}
